version: '3.8'
services:
  server:
    image: node:16
    container_name: server_auth_facebook
    ports:
      - 5000:3000
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev

  database:
    image: postgres:13
    container_name: face_auth_docker
    restart: always
    environment:
      POSTGRES_PASSWORD: facebook
      POSTGRES_USER: postgres_face
      POSTGRES_DB: postgres_face
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgres